### ISSUE TITLE
获取数据异常

### ISSUE THREAD

**Issue by KarlRaphel** [jscslld/hhu_health_report#1]
版本1.2
学号1861010110
密码（隐私保护）
使用新接口可以登录成功，但是返回的数据为空
只有这个账号有问题，不知道为什么

**Comment by KarlRaphel** [comment]
好像如果是默认密码六位数字的话用新接口都不行

**Comment by jscslld** [comment]
学长好，经过测试，发现问题出在新版的信息门户上。
通过新版信息门户中dailyreport.hhu.edu.cn进行打卡，如果您的密码为弱密码，新版信息门户会强制重定向到修改密码页面，导致无法完成自动打卡。
我的建议是您修改下默认密码，如果不修改的话，可以临时使用1.1版本打卡。
我明天也会再次更新下打卡脚本，在检测到弱密码后自动使用老接口打卡。

**Comment by jscslld** [comment]
在刚才更新的1.3版本中，添加了弱密码检测，如果是纯数字密码就会自动使用老接口打卡。
我刚才测试了下，1.3版本应该能正常使用了。

**Comment by KarlRaphel** [comment]
解决了，谢啦！
