### ISSUE TITLE
[BUG]4.6更新后报错

### ISSUE THREAD

**Issue by Yukk1No** [jscslld/hhu_health_report#3]
附上日志：
Traceback (most recent call last):
  File "report.py", line 138, in <module>
    main()
  File "report.py", line 117, in main
    add_form['tbrq'] = datetime.datetime.now(pytz.timezone('PRC')).strftime('%Y-%#m-%#d')
AttributeError: type object 'datetime.datetime' has no attribute 'datetime'
Error: Process completed with exit code 1.

**Comment by jscslld** [comment]
感谢您的反馈。经检查，此bug系修改时间生成函数后未修改导包方式导致，现已在3.0.3 bugfix版本中修复，请您在自己仓库内重新pull下最新的代码。

**Comment by Yukk1No** [comment]
感谢贡献！
