### ISSUE TITLE
研究生打卡的一个bug

### ISSUE THREAD

**Issue by hhucchenyixiao** [jscslld/hhu_health_report#8]
使用的 2.X 打卡，由于研究生的.html中也有本科生, 所以必须要注释掉前面的本科生才能正常运行
![image](https://user-images.githubusercontent.com/96377023/186658157-07ca4d50-504c-4b35-9e5a-98b5b59fdfb7.png)

**Comment by jscslld** [comment]
你好，由于我是本科生，看不到研究生的打卡界面。这个脚本的研究生打卡是之前一位学长提供了他的账号密码适配的，所以暂时我无法对这个问题进行验证。如果可以的话，你可以加一下我的QQ：2421235683，我们交流下怎么彻底解决这个问题。

**Comment by jscslld** [comment]
已修复，感谢反馈。
